# Generated by Django 6.1.1 on 2026-09-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0003_alter_comentario_usuario_alter_publicacion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado de moderación'),
        ),
        migrations.CreateModel(
            name='ReportePublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo del reporte')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='bienestar.publicacion', verbose_name='Publicación reportada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuaria que reporta')),
            ],
            options={
                'verbose_name': 'Reporte de publicación',
                'verbose_name_plural': 'Reportes de publicaciones',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bienestar.publicacion', verbose_name='Publicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuaria')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
    ]
