# Generated by Django 6.1.1 on 2026-09-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0004_publicacion_estado_reportepublicacion_megusta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20),
        ),
    ]
