# Generated by Django 6.1.1 on 2026-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0005_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
