# Generated by Django 6.1.1 on 2026-09-28 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaContenido",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "categoría de contenido",
                "verbose_name_plural": "categorías de contenido",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EjercicioPsicoeducativo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("psicoeducacion", "Psicoeducación"),
                            ("tcc", "TCC"),
                            ("actMindfulness", "ACT y Mindfulness"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("instrucciones", models.TextField()),
                ("minutos_estimados", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "ejercicio psicoeducativo",
                "verbose_name_plural": "ejercicios psicoeducativos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RutaAprendizaje",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "ruta de aprendizaje",
                "verbose_name_plural": "rutas de aprendizaje",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ContenidoEducativo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("es_premium", models.BooleanField(default=False)),
                ("fecha_publicacion", models.DateField()),
                ("resumen", models.CharField(max_length=300)),
                ("cuerpo", models.TextField()),
                ("minutos_estimados", models.PositiveSmallIntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contenidos",
                        to="educativo.categoriacontenido",
                    ),
                ),
            ],
            options={
                "verbose_name": "contenido educativo",
                "verbose_name_plural": "contenidos educativos",
                "ordering": ["fecha_publicacion", "id"],
            },
        ),
        migrations.CreateModel(
            name="RutaAprendizajeContenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                (
                    "contenido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educativo.contenidoeducativo",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pasos",
                        to="educativo.rutaaprendizaje",
                    ),
                ),
            ],
            options={
                "ordering": ["ruta", "orden"],
            },
        ),
        migrations.AddField(
            model_name="rutaaprendizaje",
            name="contenidos",
            field=models.ManyToManyField(
                related_name="rutas",
                through="educativo.RutaAprendizajeContenido",
                to="educativo.contenidoeducativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="rutaaprendizajecontenido",
            constraint=models.UniqueConstraint(
                fields=("ruta", "contenido"), name="ruta_contenido_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="rutaaprendizajecontenido",
            constraint=models.UniqueConstraint(
                fields=("ruta", "orden"), name="ruta_orden_unico"
            ),
        ),
    ]
