# Generated by Django 6.1.1 on 2026-09-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0002_catalogo_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("respuestas", models.TextField(blank=True)),
                ("utilidad", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educativo.ejerciciopsicoeducativo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_ejercicio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de ejercicio",
                "verbose_name_plural": "registros de ejercicio",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="InteraccionContenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=True)),
                ("fecha", models.DateTimeField(auto_now=True)),
                (
                    "contenido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educativo.contenidoeducativo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacciones_contenido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "interacción con contenido",
                "verbose_name_plural": "interacciones con contenido",
                "ordering": ["-fecha"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "contenido"), name="interaccion_unica"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educativo.categoriacontenido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_educativas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "preferencia de usuaria",
                "verbose_name_plural": "preferencias de usuarias",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "categoria"), name="preferencia_unica"
                    )
                ],
            },
        ),
    ]
