# Generated by Django 6.1.1 on 2026-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0004_ejercicios_modulos_guiados"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenidoeducativo",
            name="url_recurso",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="ejerciciopsicoeducativo",
            name="url_recurso",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
