# Generated by Django 6.1.1 on 2026-09-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuaria",
            name="diagnostico",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuaria",
            name="onboarding_completado",
            field=models.BooleanField(default=False),
        ),
    ]
