# Generated by Django 6.1.1 on 2026-09-26 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalizacionDolor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SintomaAsociado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroSintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("intensidad_dolor", models.PositiveSmallIntegerField()),
                (
                    "localizacion_otro_detalle",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "localizaciones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registros",
                        to="sintomas.localizaciondolor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_sintoma",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sintomas_asociados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registros",
                        to="sintomas.sintomaasociado",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
