# Generated by Django 6.1.1 on 2026-10-03 14:40

from django.db import migrations

def cargar_datos(apps, schema_editor):
    ReglaPuntos = apps.get_model('sintomas', 'ReglaPuntos')
    NivelGamificacion = apps.get_model('sintomas', 'NivelGamificacion')
    LocalizacionDolor = apps.get_model('sintomas', 'LocalizacionDolor')
    SintomaAsociado = apps.get_model('sintomas', 'SintomaAsociado')

    reglas = [
        ('registro_sintoma', 'Registro de sintomas', 10),
        ('registro_ciclo', 'Registro de ciclo', 10),
        ('checkin_emocional', 'Check-in emocional', 10),
        ('racha_7', 'Racha de 7 dias', 50),
        ('racha_30', 'Racha de 30 dias', 200),
        ('racha_90', 'Racha de 90 dias', 500),
    ]
    for clave, descripcion, puntos in reglas:
        ReglaPuntos.objects.get_or_create(
            clave=clave, defaults={'descripcion': descripcion, 'puntos': puntos}
        )

    niveles = [('Semilla', 0), ('Brote', 50), ('Capullo', 150), ('Flor', 300), ('Jardin', 600)]
    for nombre, minimo in niveles:
        NivelGamificacion.objects.get_or_create(
            puntos_minimos=minimo, defaults={'nombre': nombre}
        )

    # Catalogos de sintomas: antes solo existian en la base de quien los
    # sembro a mano; asi quedan para todo el equipo al hacer migrate.
    for nombre in ['Abdomen bajo', 'Espalda baja', 'Pelvis', 'Piernas', 'Cabeza']:
        LocalizacionDolor.objects.get_or_create(nombre=nombre)
    for nombre in ['Náuseas', 'Distensión abdominal', 'Fatiga', 'Mareo']:
        SintomaAsociado.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):
    dependencies = [
        ("sintomas", "0003_nivelgamificacion_reglapuntos_gamificacion_and_more"),
    ]

    operations = [
        migrations.RunPython(cargar_datos, migrations.RunPython.noop),
    ]
